### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by olivierobert** [ankitkalia1195/searchbot#4]
Upon review of the implementation, the overall architecture seems sound but there are not unit or UI tests to back it up.

You are free to choose between MiniTest or RSpec but tests are required at the very least for:
* Models
* Jobs
* Services
* Systems (UI) specs for the main flow to upload and see search results

**Comment by olivierobert** [comment]
@ankitkalia1195 Please work on adding tests before we can resume the review of the assignment

**Comment by ankitkalia1195** [comment]
@olivierobert Completed adding the specs, skipped UI specs for now as we discussed
