### ISSUE TITLE
Test fixtures should be stored in spec/fixture

### ISSUE THREAD

**Issue by olivierobert** [ankitkalia1195/searchbot#9]
![ankit___volumes_workspace__candidates-tests_ankit__-_____spec_models_search_report_spec_rb__ankit_](https://user-images.githubusercontent.com/696529/39111021-979c0fac-46fd-11e8-8d7a-d96d35f6c544.png)

Many tests are hard to read because the fixtures are placed in the spec files.

Bacseu fixtures take loads of space, it's better to store and group all file-based fixtures inside a sub-directory.

```ruby
RSpec.describe SearchReport do
  let(:search_report) { create(:search_report) }
  let(:google_search_parser) { GoogleSearchParser.new('new york tours') }
  let(:html_source) {  File.read(Rails.root.join('spec', 'fixtures', 'google-result-page.html')) }

  describe 'Associations' do
    it { is_expected.to belong_to(:search_task) }
    it { is_expected.to have_many(:search_results).dependent(:destroy) }
  end

  [...]
end
```

**Comment by ankitkalia1195** [comment]
Agree with this one...will make the change

**Comment by ankitkalia1195** [comment]
fixed with https://github.com/ankitkalia1195/searchbot/pull/11
